### ISSUE TITLE
associating lab and session

### ISSUE THREAD

**Issue by bendichter** [datajoint/element-lab#17]
How would I determine what labs, protocols or projects are associated with a session? I understand that there can be more than one of each associated with a single session, but I don’t see how to get that list. I would like to use this for the NWB conversion:
1. If a key for lab, protocol or project is given, ensure that it is associated with the session
2. If a key is not given, check of the list of associated labs, projects, and protocols has a length of 1, and if it does, automatically use it.

**Comment by CBroz1** [comment]
![temp__wf-sess_4](https://user-images.githubusercontent.com/9404707/152221701-2c1a99c6-3c25-4bf5-9ed3-00f59a678512.png)

The easiest way to check that a given session is associated with exactly one other item is to use a `fetch1('KEY')` call on the relevant linked table. This could be done more elegantly with `assert len(<table> & <key>)==1, <error message>`. 

Below, I get each key from exactly one session, per item 2 above.
```python
session_key=(session.Session & "subject='subject5'" 
             & "session_datetime > '2020-04-20'").fetch1('KEY')
session_user = (session.SessionExperimenter & session_key).fetch1('KEY')
session_user_lab = (lab.LabMembership & session_user).fetch1('KEY')
session_project = (session.ProjectSession & session_key).fetch1('KEY')
session_subject_protocol = (subject.Subject.Protocol & session_key).fetch1('KEY')
```

Below, I verify a provided key is associated with a session, per item 1 above. When a particular session might yield a many to one relationship, check that the provided key is in the list returned by the relevant table/session key. These statements should return `True`
```python
lab_key = (lab.Lab & "lab='LabA'")
lab_key.fetch1('lab') in (subject.Subject.Lab() & session_key).fetch('lab') 
protocol_key = (lab.Protocol & "protocol='ProtA'")
protocol_key.fetch1('protocol') in ((subject.Subject.Protocol & session_key).fetch('protocol'))
project_key = (lab.Project & "project='ProjA'").fetch1('KEY')
project_key.fetch1('project') in ((session.ProjectSession & session_key
                                   ).fetch('project'))
```
