### ISSUE TITLE
Add contribution guidelines, code of conduct, issue templates

### ISSUE THREAD

**Issue by kabilar** [datajoint/element-lab#5]
- Mirror the [datajoint/pharus](https://github.com/datajoint/pharus) repository, once it is updated based off of today's discussion.
  ```
  /.github/ISSUE_TEMPLATE/bug_report.md
  /.github/ISSUE_TEMPLATE/feature_request.md
  /.github/ISSUE_TEMPLATE/config.yml
  /CONTRIBUTING.md
  /CODE_OF_CONDUCT.md
  ```

**Comment by CBroz1** [comment]
@kabilar - Is there an existing `CODE_OF_CONDUCT.md` I can port over? Or are we not implementing?

**Comment by kabilar** [comment]
Possibly the [Contributor Covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/), which appears to be a standard in the field.
